skills_me_beta/urls.py
from django.urls import path

from skills_me_beta import views

app_name = 'skills_me_beta'

urlpatterns = [
    path('signup', views.signup_user, name='signup'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
    path('password_reset_confirm/<uidb64>/<token>', views.password_reset_confirm, name='password_reset_confirm'),
    path('current_flights/', views.currently_available_flights, name='current_flights')

]

skillsme_test/urls.py
from django.contrib import admin
from django.urls import path, include
from skills_me_beta.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('users/', include('skills_me_beta.urls')),
]

skills_me_beta/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

skills_me_beta/forms.py
from django import forms

from django.contrib.auth import password_validation
from django.contrib.auth.models import User


class SignupForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    email = forms.EmailField(max_length=200, help_text='Required', required=True)

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email', 'username', 'password',
        )


class LoginForm(forms.Form):
    username = forms.CharField(label='username or email', max_length=200, required=True,)
    password = forms.CharField(label='password', widget=forms.PasswordInput)


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(max_length=200, help_text='Enter the email you registered with')


class PasswordResetConfirmForm(forms.Form):
    error_msg = {
        'password_mismatch': 'The two passwords entered do not match'
    }
    new_password = forms.CharField(
        label='New Password', widget=forms.PasswordInput,
        strip=False, help_text=password_validation.password_validators_help_text_html
    )
    confirm_new_password = forms.CharField(
        label='Confirm New Password', widget=forms.PasswordInput,
        strip=False, help_text=password_validation.password_validators_help_text_html
    )

    # So the form can accept the "user" parameter during initialization
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordResetConfirmForm, self).__init__(*args, *kwargs)

skills_me_beta/views.py
from datetime import datetime
import requests

from django.shortcuts import render, redirect
from django.db.models.query_utils import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage, BadHeaderError
from django.http import HttpResponse

from .forms import *

# Create your views here.


def index(request):
    return render(request, 'users/index.html')


def signup_user(request):
    if request.user.is_authenticated:
        redirect('index')
    if request.method == 'POST':
        signup_form = SignupForm(data=request.POST)
        if signup_form.is_valid():
            user = signup_form.save(commit=False)
            password = signup_form.cleaned_data['password']
            user.set_password(password)
            user.save()
    signup_form = SignupForm()
    return render(request, 'users/registration.html', {'signup_form': signup_form})


def login_user(request):
    if request.user.is_authenticated:
        redirect('index')
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)

        if login_form.is_valid():
            username_email = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            # User can login with either username or password
            user_to_match = User.objects.filter(Q(username=username_email) | Q(email=username_email))

            if user_to_match:
                for user in user_to_match:
                    verified_user = authenticate(username=user.username, password=password)
                    login(request, verified_user)
                    messages.success(request, 'Your Login was successful')
                    return redirect('index')
    return render(request, 'users/login.html')


def logout_user(request):
    messages.success(request, 'Log-out successful ')
    logout(request)
    return redirect('/users/login')


@csrf_protect
def password_reset_request(request):
    if request.method == 'POST':
        user_password_reset_form = PasswordResetRequestForm(data=request.POST)
        if user_password_reset_form.is_valid():
            email = user_password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(
                Q(email__iexact=email, is_active=True, extra_fields__email_is_verified=True)
            )
            if associated_users.exists():
                for user in associated_users:
                    current_site = get_current_site(request)
                    mail_subject = 'Password Reset.'
                    message = render_to_string('users/password_reset_mail.html', {
                        'user': user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user)
                    }
                                               )

                    to_email = user.email
                    email = EmailMessage(
                        mail_subject, message, to=[to_email]
                    )
                    try:
                        email.send()
                    except BadHeaderError:
                        return HttpResponse('Invalid header found')
                return render(request, 'users/password_reset_sent.html')
    password_reset_form = PasswordResetRequestForm()
    return render(request, 'users/password_reset_request.html', {'password_reset_form': password_reset_form})


@sensitive_post_parameters()
@never_cache
def password_reset_confirm(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        valid_link = True
        if request.method == 'POST':
            password_reset_confirm_form = PasswordResetConfirmForm(user=user, data=request.POST)
            if password_reset_confirm_form.is_valid():
                    password1 = password_reset_confirm_form.cleaned_data['new_password']
                    password2 = password_reset_confirm_form.cleaned_data['confirm_new_password']
                    if password1 and password2:
                        if password1 != password2:
                            raise password_reset_confirm_form.error_msg['password_mismatch']
                    password_validation.validate_password(password2, user)
                    user.set_password(password2)
                    password_validation.password_changed(password2, user=user)
                    user.save()
                    return render(request, 'users/password_reset_successful.html')
        else:
            password_reset_confirm_form = PasswordResetConfirmForm(user)
    else:
        valid_link = False
        password_reset_confirm_form = None
    context = {
            'password_reset_confirm_form': password_reset_confirm_form,
            'valid_link': valid_link
        }
    return render(request, 'users/password_reset_confirm.html', context)


def currently_available_flights(request):
    now = datetime.now().time()
    #integer_time = int(now.strftime())
    API = "https://opensky-network.org/api/states/all"
    #parameters = integer_time
    response = requests.get(API)
    data = response.json()
    context = {
        'time': data['time'],
        'state': data['states'][2],
        'fullinfo': data['states']
    }
    #print(context)
    return render(request, 'users/current_flights.html', context)

templates/users/current_flights.html
<h2>Current flights</h2>
<h2>This hasn't been organized and beautified, just raw data here<p>
    The structure of the returned data isn't formatted nicely, it would require a little bit of cleaning
</p>
</h2>
<p>These are the Current flights<strong>Time:{{ time }}</strong>,
    <strong>{{ state }}</strong>.</p>
    <strong>{{ fullinfo }}</strong></p>

templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Skills me Beta-Test</title>
</head>
<body>
<h1>
    Welcome to Our site!!!
</h1>
<h3>
    You can view currently available flights by using the button below, also search for flights based on<br>
    date, departure and destination by using our search bar
</h3>
<a href="{% url 'skills_me_beta:signup' %}">Register Here</a><br>
<a href="{% url 'skills_me_beta:login' %}">Login Here</a><br>
<a href="{% url 'skills_me_beta:logout' %}">Logout</a> <br>
<a href="{% url 'skills_me_beta:password_reset_request' %}">Forgot Password?</a><br>
<a href="{% url 'skills_me_beta:current_flights' %}">View Current Flights</a>
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% if messages %}
    <p>
    {% for messagge in messages %}
    <strong>{{ messagge }}</strong>
    {% endfor %}
    </p>
{% endif %}
<form class="form-horizontal" role="form" action="{% url 'skills_me_beta:login' %}" method="post">
    {%  csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_username">
            Username:
        </label>
        <div class="col-sm-10">
            <input id="id_username" maxlength="30" name="username" type="text">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_password">
            Password:
        </label>
        <div class="col-sm-10">
            <input id="id_password" maxlength="100" name="password" type="password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button><br>
            <span><a href="{% url 'skills_me_beta:password_reset_request' %}">Forgot Password</a></span><br>
            <span>Not registered?, Do so <a href="{% url 'skills_me_beta:signup' %}">Here</a></span>
        </div>

    </div>


</form>
</body>
</html>

templates/users/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset Confirm</title>
</head>
<body>
{% load i18n static %}
{% if valid_link %}

<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <input class="hidden" type="hidden" autocomplete="username" value="{{ password_reset_confirm_form.user.get_username }}">
    <div class="form-row field-password1">
        {{ password_reset_confirm_form.new_password.errors }}
        <label for="id_new_password">{% translate 'New password:' %}</label>
        {{ password_reset_confirm_form.new_password }}
    </div>
    <div class="form-row field-password2">
        {{ password_reset_confirm_form.confirm_new_password.errors }}
        <label for="id_confirm_new_password">{% translate 'Confirm password:' %}</label>
        {{ password_reset_confirm_form.confirm_new_password }}
    </div>
    {{ password_reset_confirm_form.new_password.help_text }}
    <input type="submit" value="{% translate 'Change my password' %}">
</fieldset>
</form>

{% else %}

<p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

</body>
</html>

templates/users/password_reset_mail.html
{% autoescape off %}
Hello {{ user.username }},
    We received a request from you to reset your password associated with this email address
    Please click on the link to reset your password on our Platform.
    http://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

    Note that this link can only be used once, if you need to reset your password again visit
    http://{{ domain }}
{% endautoescape %}

templates/users/password_reset_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset</title>
</head>
<body>
<h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST" action="{% url 'skills_me_beta:password_reset_request' %}">
    {% csrf_token %}
    {{ password_reset_form }}
    <input type="submit" value="Send me instructions!">
  </form>

</body>
</html>

templates/users/password_reset_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset Sent</title>
</head>
<body>
<h1>
    Check your Mail
    <h3>
        We Just sent you instructions on how to reset your password
    </h3>
</h1>

</body>
</html>

templates/users/password_reset_successful.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset Success</title>
</head>
<body>
<h1>Congrats
    <h3>
        your password has been successfully changed, Please Login with the new password
    </h3>
</h1>
<a href="{% url 'skills_me_beta:login' %}"></a>
</body>
</html>

templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Skills me Beta-Flight test app-Registration</title>
</head>
<body>
<h1>
    Register for an account Here<p>Have an account? <br>Then<a href="{% url 'skills_me_beta:login'%}"> login</a></p>
    {% if error_msg %}
        <p>
        <strong>
            {{ error_msg }}
        </strong>
        </p>
    {% endif %}
    <form enctype="multipart/form-data" class="form-horizontal" role="form" action="{% url 'skills_me_beta:signup' %}" method="post">
        {% csrf_token %}
        {% for field in signup_form%}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{ field.errors }}</span>
                </div>
                <label class="control-label col-sm-2" for="">{{ field.label_tag }}</label>
                <div class="col-sm-10">{{ field }}</div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</h1>
</body>
</html>